name: Build-Windows-Binary
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build PowerShell Windows Binary
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Bootstrap and Build
        shell: pwsh
        run: |
          Import-Module ./build.psm1
          Start-PSBootstrap -Scenario Both
          Start-PSBuild -Configuration Release -UseNuGetOrg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PowerShell-Windows-Binary
          path: src/powershell-win-core/bin/Release/**/publish/
